### ISSUE TITLE
Mobile Optimization 

### ISSUE THREAD

**Issue by CertifiedRice** [CertifiedRice/certifiedrice-website#2]
Optimizing the website for mobile! 

Currently the [portfolio page](https://certifiedrice.tacobyte.dev/portfolio)

Example on CSS of fixing
```css
@media (max-width: 6in)
{
    .box {
      margin-left: 90px;
      margin-right: 30px;
      margin-bottom: fill;
    }
}
```

Currently, some of the projects are cut out on mobile(iPhone 11 is what I am testing it on) 
The CSS above might be the solution to fixing it, it helped it a little bit but is not fully resolved yet.
